#!/usr/bin/env python3
"""LaTeX reach table for the paper's RQ4, generated from every library's cells.json and the
defect manifest.

Writes results/rq3_coverage/rq4_tables.tex with:
  \\ValidatorReachTable  -- all cells: suite status; plan/build/export funnel; function, region,
                            and unique-region reach; and clustered defect ids.
Raw candidate counts intentionally stay out: they count inputs before clustering, not defects.
Nothing under c2rust_paper/ is written.

usage: scripts/rq4/paper_tables.py [--out results/rq3_coverage/rq4_tables.tex]
"""
from __future__ import annotations

import argparse
import json
from pathlib import Path

ROOT = Path(__file__).resolve().parents[2]
RQ4 = ROOT / "results" / "rq3_coverage"
MANIFEST = ROOT / "results" / "rq4_effectiveness" / "defect_manifest.json"
LIBS = ["bzip2", "genann", "cjson", "lil", "tulip", "qsort", "urlparser", "quadtree", "lodepng", "optipng"]
LIB_TEX = {"bzip2": "bzip2", "genann": "genann", "cjson": "cJSON", "lil": "lil", "tulip": "tulip",
           "qsort": "qsort", "urlparser": "urlparser", "quadtree": "quadtree", "lodepng": "lodepng", "optipng": "optipng"}
TOOL_TEX = {"c2rust": "c2rust", "laertes": "Laertes", "crown": "CROWN", "c2saferrust": "C2SaferRust",
            "sactor": "SACTOR", "ptrtrans": "PtrTrans"}
NEW_IN_RQ4 = {"C8", "C9", "C10", "C11", "S15"}


def suite_status(c: dict) -> str:
    t = str(c.get("tests", ""))
    if t.startswith("PASS"):
        return "P"
    if "UNAVAILABLE" in t:
        return "--"
    if "ADAPTER" in t:
        return "A"
    if "FAIL" in t:
        return "F"
    return t.lower() or "?"


def defects_for(lib: str, tool: str, defects: list[dict], cands: list[dict]) -> str:
    key = f"rq3_coverage/{lib}/{tool}"
    ids = []
    for d in defects:
        ev = (d.get("evidence") or "") + " " + (d.get("provenance_note") or "")
        if key in ev:
            label = d["id"]
            ids.append(("\\textbf{%s}" % label) if label in NEW_IN_RQ4 else label)
    for c in cands:
        if key in (c.get("evidence") or ""):
            ids.append(f"{c['id']}$^{{\\dagger}}$")
    return ", ".join(ids) if ids else "--"

def main() -> int:
    ap = argparse.ArgumentParser()
    ap.add_argument("--out", default=str(RQ4 / "rq4_tables.tex"))
    a = ap.parse_args()
    m = json.loads(MANIFEST.read_text()) if MANIFEST.exists() else {}
    defects, cands = m.get("defects", []), m.get("candidates", [])
    rows = []
    for lib in LIBS:
        p = RQ4 / lib / "cells.json"
        if not p.exists():
            continue
        for c in json.loads(p.read_text()):
            if "function" not in c:
                continue
            suite = suite_status(c)
            fn, reg = c["function"], c["region"]
            fn_cov = f"{100 * fn['tests_cov']:.1f}/{100 * fn['ours_cov']:.1f}" if suite == "P" else f"--/{100 * fn['ours_cov']:.1f}"
            reg_cov = f"{100 * reg['tests_cov']:.1f}/{100 * reg['ours_cov']:.1f}" if suite == "P" else f"--/{100 * reg['ours_cov']:.1f}"
            unique = (f"{100 * reg['only_tests'] / reg['universe']:.1f}/"
                      f"{100 * reg['only_ours'] / reg['universe']:.1f}") if suite == "P" else "--"
            rows.append(dict(
                lib=LIB_TEX[lib], tool=TOOL_TEX.get(c["tool"], c["tool"]), suite=suite,
                planned=c["planned"], matched=c["matched"], exported=c["exported"],
                built=c["built"], fn_cov=fn_cov, reg_cov=reg_cov, unique=unique,
                defects=defects_for(lib, c["tool"], defects, cands),
            ))
    L = []
    P = L.append
    P("% GENERATED by scripts/rq4/paper_tables.py from results/rq3_coverage/*/cells.json and")
    P("% results/rq4_effectiveness/defect_manifest.json. Do not edit by hand; regenerate.")
    P("% Requires booktabs, multirow, colortbl (as")
    P("% figures_tables.tex already does). Paste into figures_tables.tex or \\input this file.")
    P("\\newcommand{\\ValidatorReachTable}{%")
    P("\\begin{center}")
    P("\\begin{minipage}{\\textwidth}")
    P("\\centering")
    P("\\captionof{table}{Reach of generated campaigns across all 19 artifacts. Plan/match and")
    P("build/export report the harness funnel; T/O is tests/ours. Unique regions are shown only when the")
    P("suite passes. Suite status: P=pass, F=fail, A=adapter failure, --=unavailable. Bold defect ids")
    P("were first confirmed by these campaigns; $^{\\dagger}$ marks a held-out candidate.}")
    P("\\label{tab:validator-reach}")
    P("\\tiny")
    P("\\setlength{\\tabcolsep}{1.7pt}")
    P("\\renewcommand{\\arraystretch}{1.12}")
    P("\\begin{tabular}{@{}llccccccl@{}}")
    P("\\toprule")
    P("\\rowcolor{gray!12}")
    P("\\textbf{Library} & \\textbf{Translation} & \\textbf{Suite} &")
    P("\\shortstack{\\textbf{Plan/}\\\\\\textbf{match}} &")
    P("\\shortstack{\\textbf{Build/}\\\\\\textbf{export}} &")
    P("\\shortstack{\\textbf{Function}\\\\\\textbf{T/O (\\%)}} &")
    P("\\shortstack{\\textbf{Region}\\\\\\textbf{T/O (\\%)}} &")
    P("\\shortstack{\\textbf{Unique reg.}\\\\\\textbf{T/O (\\%)}} & \\textbf{Defects} \\\\")
    P("\\midrule")
    cur = None
    for i, r in enumerate(rows):
        first = r["lib"] != cur
        cur = r["lib"]
        if first and i:
            P("\\addlinespace[2pt]")
        libcell = r["lib"] if first else ""
        P(f"{libcell} & {r['tool']} & {r['suite']} & {r['planned']}/{r['matched']} & "
          f"{r['built']}/{r['exported']} & "
          f"{r['fn_cov']} & {r['reg_cov']} & {r['unique']} & {r['defects']} \\\\")
    P("\\bottomrule")
    P("\\end{tabular}")
    P("\\end{minipage}")
    P("\\end{center}}")
    Path(a.out).write_text("\n".join(L) + "\n")
    print(f"wrote {a.out}: {len(rows)} rows")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
