#!/usr/bin/env python3
"""LaTeX reach table for the paper's RQ4, generated from verified cells.json files.

Writes results/rq3_coverage/rq4_tables.tex with:
  \\ValidatorReachTable  -- matched/planned/built stages and function/region reach.
Nothing under c2rust_paper/ is written.

usage: scripts/rq4/paper_tables.py [--out results/rq3_coverage/rq4_tables.tex]
"""
from __future__ import annotations

import argparse
import json
from pathlib import Path

ROOT = Path(__file__).resolve().parents[2]
RQ4 = ROOT / "results" / "rq3_coverage"
LIBS = ["bzip2", "genann", "cjson", "lil", "tulip", "qsort", "quadtree"]
LIB_TEX = {"bzip2": "bzip2", "genann": "genann", "cjson": "cJSON", "lil": "lil", "tulip": "tulip",
           "qsort": "qsort", "urlparser": "urlparser", "quadtree": "quadtree", "lodepng": "lodepng", "optipng": "optipng"}
TOOL_TEX = {"c2rust": "c2rust", "laertes": "Laertes", "crown": "CROWN", "c2saferrust": "C2SaferRust",
            "sactor": "SACTOR", "ptrtrans": "PtrTrans"}

def main() -> int:
    ap = argparse.ArgumentParser()
    ap.add_argument("--out", default=str(RQ4 / "rq4_tables.tex"))
    a = ap.parse_args()
    rows = []
    for lib in LIBS:
        p = RQ4 / lib / "cells.json"
        if not p.exists():
            continue
        for c in json.loads(p.read_text()):
            if "function" not in c:
                continue
            fn, reg = c["function"], c["region"]
            rows.append(dict(
                lib=LIB_TEX[lib], tool=TOOL_TEX.get(c["tool"], c["tool"]),
                planned=c["planned"], matched=c["matched"],
                built=c["built"], fn_cov=f"{100 * fn['ours_cov']:.1f}",
                reg_cov=f"{100 * reg['ours_cov']:.1f}",
            ))
    L = []
    P = L.append
    P("% GENERATED by scripts/rq4/paper_tables.py from results/rq3_coverage/*/cells.json.")
    P("% Do not edit by hand; regenerate.")
    P("% Requires booktabs, multirow, colortbl (as")
    P("% figures_tables.tex already does). Paste into figures_tables.tex or \\input this file.")
    P("\\newcommand{\\ValidatorReachTable}{%")
    P("\\begin{center}")
    P("\\begin{minipage}{\\textwidth}")
    P("\\centering")
    P(f"\\captionof{{table}}{{Reach of fixed-budget generated campaigns across {len(LIBS)} applications")
    P(f"and {len(rows)} verified artifacts. M/P/B is matched/planned/built. Each coverage")
    P("percentage uses the corresponding translated artifact's instrumented code map.}")
    P("\\label{tab:validator-reach}")
    P("\\scriptsize")
    P("\\setlength{\\tabcolsep}{5.2pt}")
    P("\\renewcommand{\\arraystretch}{1.12}")
    P("\\begin{tabular}{@{}llccc@{}}")
    P("\\toprule")
    P("\\rowcolor{gray!12}")
    P("\\textbf{Application} & \\textbf{Translation} &")
    P("\\shortstack{\\textbf{Boundary stages}\\\\\\textbf{M/P/B}} &")
    P("\\shortstack{\\textbf{Function}\\\\\\textbf{coverage (\\%)}} &")
    P("\\shortstack{\\textbf{Region}\\\\\\textbf{coverage (\\%)}} \\\\")
    P("\\midrule")
    cur = None
    for i, r in enumerate(rows):
        first = r["lib"] != cur
        cur = r["lib"]
        if first and i:
            P("\\addlinespace[2pt]")
        libcell = r["lib"] if first else ""
        P(f"{libcell} & {r['tool']} & {r['matched']}/{r['planned']}/{r['built']} & "
          f"{r['fn_cov']} & {r['reg_cov']} \\\\")
    P("\\bottomrule")
    P("\\end{tabular}")
    P("\\end{minipage}")
    P("\\end{center}}")
    Path(a.out).write_text("\n".join(L) + "\n")
    print(f"wrote {a.out}: {len(rows)} rows")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
