#!/usr/bin/env python3
"""LaTeX table macros for the paper's RQ4, generated from every library's cells.json and the
defect manifest -- so the paper's numbers and results/rq3_coverage/ cannot drift apart.

Writes results/rq3_coverage/rq4_tables.tex with:
  \\ValidatorReachTable  -- all cells: suite status, funnel (planned/matched, built), validator
                            coverage of the translation's universe, confirmed candidates, defects
The paired comparison (\\CoverageComparisonTable) stays hand-maintained in the paper; this file is
meant to be \\input or pasted into figures_tables.tex. Nothing under c2rust_paper/ is written.

usage: scripts/rq4/paper_tables.py [--out results/rq3_coverage/rq4_tables.tex]
"""
from __future__ import annotations

import argparse
import json
from pathlib import Path

ROOT = Path(__file__).resolve().parents[2]
RQ4 = ROOT / "results" / "rq3_coverage"
MANIFEST = ROOT / "results" / "rq4_effectiveness" / "defect_manifest.json"
LIBS = ["bzip2", "genann", "cjson", "lil", "tulip"]
LIB_TEX = {"bzip2": "bzip2", "genann": "genann", "cjson": "cJSON", "lil": "lil", "tulip": "tulip"}
TOOL_TEX = {"c2rust": "c2rust", "laertes": "Laertes", "crown": "CROWN", "c2saferrust": "C2SaferRust",
            "sactor": "SACTOR", "ptrtrans": "PtrTrans"}
NEW_IN_RQ4 = {"C8", "C9", "C10", "C11", "S15"}


def suite_status(c: dict) -> str:
    t = str(c.get("tests", ""))
    if t.startswith("PASS"):
        return "pass"
    if "UNAVAILABLE" in t:
        return "none"
    if "ADAPTER" in t:
        return "adapter"
    if "FAIL" in t:
        return "fails"
    return t.lower() or "?"


def defects_for(lib: str, tool: str, defects: list[dict], cands: list[dict]) -> str:
    key = f"rq3_coverage/{lib}/{tool}"
    ids = []
    for d in defects:
        ev = (d.get("evidence") or "") + " " + (d.get("provenance_note") or "")
        if key in ev:
            ids.append(("\\textbf{%s}" % d["id"]) if d["id"] in NEW_IN_RQ4 else d["id"])
    for c in cands:
        if key in (c.get("evidence") or ""):
            ids.append(f"{c['id']}$^{{\\dagger}}$")
    return ", ".join(ids) if ids else "--"


def main() -> int:
    ap = argparse.ArgumentParser()
    ap.add_argument("--out", default=str(RQ4 / "rq4_tables.tex"))
    a = ap.parse_args()
    m = json.loads(MANIFEST.read_text()) if MANIFEST.exists() else {}
    defects, cands = m.get("defects", []), m.get("candidates", [])
    rows = []
    for lib in LIBS:
        p = RQ4 / lib / "cells.json"
        if not p.exists():
            continue
        for c in json.loads(p.read_text()):
            if "function" not in c:
                continue
            t = (c.get("confirm") or {}).get("total") or {}
            rows.append(dict(
                lib=LIB_TEX[lib], tool=TOOL_TEX.get(c["tool"], c["tool"]), suite=suite_status(c),
                planned=c["planned"], matched=c["matched"], built=c["built"], corpus=c["corpus"],
                fn=100 * c["function"]["ours_cov"], reg=100 * c["region"]["ours_cov"],
                cd=t.get("confirmed_divergence", 0), ct=t.get("confirmed_termination", 0),
                defects=defects_for(lib, c["tool"], defects, cands)))
    L = []
    P = L.append
    P("% GENERATED by scripts/rq4/paper_tables.py from results/rq3_coverage/*/cells.json and the")
    P("% defect manifest. Do not edit by hand; regenerate. Requires booktabs, multirow, colortbl (as")
    P("% figures_tables.tex already does). Paste into figures_tables.tex or \\input this file.")
    P("\\newcommand{\\ValidatorReachTable}{%")
    P("\\begin{center}")
    P("\\begin{minipage}{\\textwidth}")
    P("\\centering")
    P("\\captionof{table}{Every RQ4 cell: the suite's status, how many matched boundaries the planner")
    P("could construct and build, the validator's coverage of the translation's own universe, and")
    P("what its candidates became. Coverage is of the translation, against the passing suite's build")
    P("where the suite passes and the translation's own instrumented objects otherwise; a failed suite")
    P("is never 0\\%. Confirmed counts are the cell's labelled confirmation sample before clustering;")
    P("bold defect ids were first found here, the others were catalogued earlier and re-found.")
    P("$^{\\dagger}$ held-out candidate.}")
    P("\\label{tab:validator-reach}")
    P("\\scriptsize")
    P("\\setlength{\\tabcolsep}{3.6pt}")
    P("\\renewcommand{\\arraystretch}{1.12}")
    P("\\begin{tabular}{@{}llcrrrrrrl@{}}")
    P("\\toprule")
    P("\\rowcolor{gray!12}")
    P("\\textbf{Library} & \\textbf{Translation} & \\textbf{Suite} & "
      "\\shortstack{\\textbf{Planned /}\\\\\\textbf{matched}} & \\textbf{Built} & \\textbf{Corpus} & "
      "\\shortstack{\\textbf{Fn cov.}\\\\\\textbf{O (\\%)}} & \\shortstack{\\textbf{Region cov.}\\\\\\textbf{O (\\%)}} & "
      "\\shortstack{\\textbf{Confirmed}\\\\\\textbf{div. / term.}} & \\textbf{Defects} \\\\")
    P("\\midrule")
    cur = None
    for i, r in enumerate(rows):
        first = r["lib"] != cur
        cur = r["lib"]
        if first and i:
            P("\\addlinespace[2pt]")
        libcell = r["lib"] if first else ""
        P(f"{libcell} & {r['tool']} & {r['suite']} & {r['planned']}/{r['matched']} & {r['built']} & "
          f"{r['corpus']:,} & {r['fn']:.1f} & {r['reg']:.1f} & {r['cd']} / {r['ct']} & {r['defects']} \\\\")
    P("\\bottomrule")
    P("\\end{tabular}")
    P("\\end{minipage}")
    P("\\end{center}}")
    Path(a.out).write_text("\n".join(L) + "\n")
    print(f"wrote {a.out}: {len(rows)} rows")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
