#!/usr/bin/env python3
"""Package remaining bzip2 buffer-API defects for released FLOURINE.

The adapters expose the original return value and keep source and destination
storage inside one generated fixed array.  FLOURINE therefore observes both
the scalar return and mutations to the destination bytes without a custom
comparator.  Lengths are derived from generated bytes and kept in bounds.
"""

from __future__ import annotations

import hashlib
import json
import re
from pathlib import Path


ROOT = Path("/home/yunzez/c2rust_testing")
OUT_ROOT = ROOT / "results/baseline_artifacts/adapters/flourine"
C_FILES = (
    "bzlib.h",
    "bzlib_private.h",
    "blocksort.c",
    "huffman.c",
    "crctable.c",
    "randtable.c",
    "compress.c",
    "decompress.c",
    "bzlib.c",
)


def sha256(path: Path) -> str:
    return hashlib.sha256(path.read_bytes()).hexdigest()


def without_includes(source: str) -> str:
    return re.sub(
        r"^\s*#\s*include\s*[<\"][^>\"]+[>\"]\s*$",
        "",
        source,
        flags=re.MULTILINE,
    )


def c_dependency_unit(pair: Path) -> str:
    source = pair / "source"
    return "\n\n".join(without_includes((source / name).read_text()) for name in C_FILES)


def rust_dependency_unit(pair: Path) -> str:
    path = next((pair / "translated").glob("*.rs"))
    source = path.read_text()
    return re.sub(r"(?ms)^#!\[[^\]]*\]\s*", "", source).rstrip() + "\n"


def compress_c() -> str:
    return r'''

int bzbuff_compress_observe(int8_t packet[322])
{
    unsigned int source_length = ((unsigned char)packet[0]) % 64;
    unsigned int destination_length = 256;
    int result = BZ2_bzBuffToBuffCompress(
        (char *)&packet[65],
        &destination_length,
        (char *)&packet[1],
        source_length,
        1,
        0,
        30);
    memcpy(&packet[0], &destination_length, sizeof(destination_length));
    return result;
}
'''


def compress_rust(raw_name: str) -> str:
    return f'''#![feature(core_intrinsics)]
#![feature(extern_types)]
#![feature(linkage)]
#![feature(c_variadic)]
#![feature(register_tool)]
#![register_tool(c2rust)]

include!["/input/{raw_name}"];

#[no_mangle]
pub fn bzbuff_compress_observe(packet: &mut [i8; 322]) -> i32 {{
    let source_length = (packet[0] as u8 % 64) as u32;
    let mut destination_length = 256u32;
    let result = unsafe {{
        BZ2_bzBuffToBuffCompress(
            packet.as_mut_ptr().add(65),
            Some(&mut destination_length),
            packet.as_mut_ptr().add(1),
            source_length,
            1,
            0,
            30,
        )
    }};
    let bytes = destination_length.to_ne_bytes();
    for (slot, value) in packet[..4].iter_mut().zip(bytes) {{
        *slot = value as i8;
    }}
    result
}}
'''


def decompress_c() -> str:
    return r'''

int bzbuff_decompress_observe(int8_t packet[450])
{
    unsigned int source_length = 1 + ((unsigned char)packet[0]) % 192;
    unsigned int destination_length = 256;
    int small = ((unsigned char)packet[449]) & 1;
    int result = BZ2_bzBuffToBuffDecompress(
        (char *)&packet[193],
        &destination_length,
        (char *)&packet[1],
        source_length,
        small,
        0);
    memcpy(&packet[0], &destination_length, sizeof(destination_length));
    return result;
}
'''


def decompress_rust(raw_name: str) -> str:
    return f'''#![feature(core_intrinsics)]
#![feature(extern_types)]
#![feature(linkage)]
#![feature(c_variadic)]
#![feature(register_tool)]
#![register_tool(c2rust)]

include!["/input/{raw_name}"];

#[no_mangle]
pub fn bzbuff_decompress_observe(packet: &mut [i8; 450]) -> i32 {{
    let source_length = 1 + (packet[0] as u8 % 192) as u32;
    let small = (packet[449] as u8 & 1) as i32;
    let mut destination_length = 256u32;
    let result = unsafe {{
        BZ2_bzBuffToBuffDecompress(
            packet.as_mut_ptr().add(193),
            Some(&mut destination_length),
            packet.as_mut_ptr().add(1),
            source_length,
            small,
            0,
        )
    }};
    let bytes = destination_length.to_ne_bytes();
    for (slot, value) in packet[..4].iter_mut().zip(bytes) {{
        *slot = value as i8;
    }}
    result
}}
'''


def emit(defect: str, pair_name: str, mode: str) -> None:
    pair = ROOT / "benchmark/pairs/rq4" / pair_name
    out = OUT_ROOT / defect
    input_dir = out / "input"
    input_dir.mkdir(parents=True, exist_ok=True)

    if mode == "compress":
        target = "bzbuff_compress_observe"
        size = 322
        c_wrapper = compress_c()
        rust_surface = compress_rust(f"{target}_raw.inc")
        contract = (
            "Use generated source and destination bytes, derive source length in [0,63], "
            "provide 256 bytes of destination capacity, and expose the original return, "
            "destination length, and destination bytes."
        )
    elif mode == "decompress":
        target = "bzbuff_decompress_observe"
        size = 450
        c_wrapper = decompress_c()
        rust_surface = decompress_rust(f"{target}_raw.inc")
        contract = (
            "Use generated source and destination bytes, derive source length in [1,192] "
            "and small in {0,1}, provide 256 bytes of destination capacity, and expose "
            "the original return, destination length, and destination bytes."
        )
    else:
        raise ValueError(mode)

    json_path = input_dir / f"{target}.json"
    rust_path = input_dir / f"{target}.rs"
    raw_path = input_dir / f"{target}_raw.inc"
    json_path.write_text(
        json.dumps(
            {
                "Includes": [
                    "#include <ctype.h>",
                    "#include <stdint.h>",
                    "#include <stdio.h>",
                    "#include <stdlib.h>",
                    "#include <string.h>",
                ],
                "Defines": [],
                "TypeDefs": [],
                "Globals": [],
                "Structs": [],
                "Function Declarations": [f"int {target}(int8_t packet[{size}]);"],
                "Function Implementations": [c_dependency_unit(pair) + c_wrapper],
                "Enums": [],
            },
            indent=2,
        )
        + "\n"
    )
    raw_path.write_text(rust_dependency_unit(pair))
    rust_path.write_text(rust_surface)
    translated = next((pair / "translated").glob("*.rs"))
    metadata = {
        "schema_version": 1,
        "defect": defect,
        "baseline": "flourine",
        "target": target,
        "adapter_kind": "documented_per_function_json_with_bounded_buffer_wrapper",
        "semantic_rewrite": False,
        "known_witness_encoded": False,
        "sources": {
            "c": str((pair / "source/bzlib.c").relative_to(ROOT)),
            "rust": str(translated.relative_to(ROOT)),
        },
        "wrapper_contract": contract,
        "input_sha256": {
            path.name: sha256(path) for path in (json_path, rust_path, raw_path)
        },
    }
    (out / "adapter.json").write_text(json.dumps(metadata, indent=2) + "\n")


def main() -> None:
    emit("C8", "bzip2_laertes", "compress")
    emit("C7", "bzip2_crown", "compress")
    emit("S11", "bzip2_crown", "decompress")


if __name__ == "__main__":
    main()
