#!/usr/bin/env python3
"""Package six function-local non-pilot defects for FLOURINE expansion."""

from __future__ import annotations

import hashlib
import json
from pathlib import Path


ROOT = Path("/home/yunzez/c2rust_testing")


def sha256(path: Path) -> str:
    return hashlib.sha256(path.read_bytes()).hexdigest()


def brace_item(text: str, marker: str) -> str:
    start = text.index(marker)
    brace = text.index("{", start)
    depth = 0
    for index in range(brace, len(text)):
        if text[index] == "{":
            depth += 1
        elif text[index] == "}":
            depth -= 1
            if depth == 0:
                return text[start : index + 1]
    raise ValueError(marker)


def emit(
    defect: str,
    target: str,
    includes: list[str],
    defines: list[str],
    declarations: list[str],
    c_code: str,
    rust_prelude: str,
    rust_exact: str,
    rust_wrapper: str,
    sources: dict[str, str],
    contract: str,
) -> None:
    out = ROOT / f"results/baseline_artifacts/adapters/flourine/{defect}"
    input_dir = out / "input"
    input_dir.mkdir(parents=True, exist_ok=True)
    json_path = input_dir / f"{target}.json"
    rust_path = input_dir / f"{target}.rs"
    raw_path = input_dir / f"{target}_raw.inc"
    json_path.write_text(
        json.dumps(
            {
                "Includes": includes,
                "Defines": defines,
                "TypeDefs": [],
                "Globals": [],
                "Structs": [],
                "Function Declarations": declarations,
                "Function Implementations": [c_code],
                "Enums": [],
            },
            indent=2,
        )
        + "\n"
    )
    raw_path.write_text(rust_exact.rstrip() + "\n")
    rust_path.write_text(
        rust_prelude.rstrip()
        + f'\n\ninclude!["/input/{raw_path.name}"];\n\n'
        + rust_wrapper.rstrip()
        + "\n"
    )
    metadata = {
        "schema_version": 1,
        "defect": defect,
        "baseline": "flourine",
        "target": target,
        "adapter_kind": "documented_per_function_json_with_safe_fixed_shape_wrapper",
        "semantic_rewrite": False,
        "known_witness_encoded": False,
        "sources": sources,
        "wrapper_contract": contract,
        "input_sha256": {
            path.name: sha256(path) for path in [json_path, rust_path, raw_path]
        },
    }
    (out / "adapter.json").write_text(json.dumps(metadata, indent=2) + "\n")


def make_c2() -> None:
    c_path = ROOT / "benchmark/pairs/rq4/urlparser_c2saferrust/source/url.h"
    r_path = ROOT / "benchmark/pairs/rq4/urlparser_c2saferrust/translated/urlparser_c2saferrust.rs"
    c_fn = brace_item(c_path.read_text(), "bool\nurl_is_ssh (char *str) {")
    r_fn = brace_item(r_path.read_text(), "pub fn url_is_ssh")
    emit(
        "C2", "url_is_ssh_valid",
        ["#include <stdbool.h>", "#include <stdint.h>", "#include <stdlib.h>", "#include <string.h>"], [],
        ["bool url_is_ssh_valid(int8_t value[16]);"],
        c_fn + "\n\nbool url_is_ssh_valid(int8_t value[16]) { value[15] = 0; return url_is_ssh((char *)value); }",
        "use std::ffi::CStr;",
        r_fn,
        "#[no_mangle]\npub fn url_is_ssh_valid(value: &mut [i8; 16]) -> bool { value[15] = 0; url_is_ssh(value.as_mut_ptr()) }",
        {"c": str(c_path.relative_to(ROOT)), "rust": str(r_path.relative_to(ROOT))},
        "Force a 16-byte generated byte string to be NUL-terminated and call the exact target on both sides.",
    )


def make_c4() -> None:
    c_path = ROOT / "tools/frameworks/crown/c-code/bzip2/bzip2recover.c"
    r_path = ROOT / "tools/frameworks/c2saferrust/laertes_benchmarks/bzip2_WIP/bzip2recover.rs"
    c_fn = brace_item(c_path.read_text(), "static Bool endsInBz2")
    r_fn = brace_item(r_path.read_text(), "fn endsInBz2")
    emit(
        "C4", "ends_in_bz2_valid",
        ["#include <stdint.h>", "#include <string.h>"], ["#define False 0"],
        ["int ends_in_bz2_valid(int8_t value[16]);"],
        (
            "typedef char Char; typedef int Bool; typedef int Int32;\n"
            + c_fn
            + "\n\nint ends_in_bz2_valid(int8_t value[16]) "
              "{ value[15] = 0; return endsInBz2((Char *)value); }"
        ),
        "", r_fn,
        (
            "#[no_mangle]\n"
            "pub fn ends_in_bz2_valid(value: &mut [i8; 16]) -> i32 "
            "{ value[15] = 0; endsInBz2(value.as_mut_ptr()) }"
        ),
        {"c": str(c_path.relative_to(ROOT)), "rust": str(r_path.relative_to(ROOT))},
        (
            "Force a generated 16-byte filename to be NUL-terminated and call the exact "
            "target on both sides; no suffix or byte value is fixed."
        ),
    )


def make_s15() -> None:
    c_path = ROOT / "benchmark/pairs/rq4/tulip_c2saferrust/source/indicators/adx.c"
    r_path = ROOT / "benchmark/pairs/rq4/tulip_c2saferrust/translated/tulip_c2saferrust.rs"
    c_fn = brace_item(c_path.read_text(), "int ti_adx_start")
    r_fn = brace_item(r_path.read_text(), 'pub extern "C" fn ti_adx_start')
    emit(
        "S15", "ti_adx_start_valid", ["#include <stdint.h>"], ["#define TI_REAL double"],
        ["int ti_adx_start_valid(double options[1]);"],
        c_fn + "\n\nint ti_adx_start_valid(double options[1]) { return ti_adx_start(options); }",
        "", r_fn,
        "#[no_mangle]\npub fn ti_adx_start_valid(options: &mut [f64; 1]) -> i32 { ti_adx_start(options.as_ptr()) }",
        {"c": str(c_path.relative_to(ROOT)), "rust": str(r_path.relative_to(ROOT))},
        "Expose the one-element options array as a fixed safe reference; no option value is fixed.",
    )


def make_s14() -> None:
    c_path = ROOT / "benchmark/pairs/rq4/bzip2_c2saferrust/source/blocksort.c"
    r_path = ROOT / "benchmark/pairs/rq4/bzip2_c2saferrust/translated/bzip2_c2saferrust.rs"
    c_fn = brace_item(c_path.read_text(), "UChar mmed3")
    r_fn = brace_item(r_path.read_text(), " fn mmed3")
    emit(
        "S14", "mmed3_valid", [], [], ["unsigned char mmed3_valid(unsigned char a, unsigned char b, unsigned char c);"],
        "typedef unsigned char UChar;\n" + c_fn + "\n\nunsigned char mmed3_valid(unsigned char a, unsigned char b, unsigned char c) { return mmed3(a,b,c); }",
        "", r_fn,
        "#[no_mangle]\npub fn mmed3_valid(a: u8, b: u8, c: u8) -> u8 { mmed3(a,b,c) }",
        {"c": str(c_path.relative_to(ROOT)), "rust": str(r_path.relative_to(ROOT))},
        "Forward three artifact-generated bytes to the exact helper.",
    )


def make_c13() -> None:
    c_path = ROOT / "benchmark/pairs/rq4/optipng_c2saferrust/source/optipng/optim.c"
    r_path = ROOT / "benchmark/pairs/rq4/optipng_c2saferrust/translated/optipng_c2saferrust.rs"
    c_fn = brace_item(c_path.read_text(), "opng_free(void *ptr)")
    r_fn = brace_item(r_path.read_text(), "fn opng_free(ptr:")
    emit(
        "C13", "opng_free_null", ["#include <stdlib.h>"], [], ["void opng_free_null(void);"],
        c_fn + "\n\nvoid opng_free_null(void) { opng_free(NULL); }", "", r_fn,
        "#[no_mangle]\npub fn opng_free_null() { opng_free(std::ptr::null_mut()); }",
        {"c": str(c_path.relative_to(ROOT)), "rust": str(r_path.relative_to(ROOT))},
        "Exercise the documented free(NULL) contract with no generated arguments; the wrapper performs only the call.",
    )


def make_s16() -> None:
    c_path = ROOT / "benchmark/pairs/rq4/optipng_c2saferrust/source/optipng/optipng.c"
    r_path = ROOT / "benchmark/pairs/rq4/optipng_c2saferrust/translated/optipng_c2saferrust.rs"
    c_fn = brace_item(c_path.read_text(), "opng_strcasecmp(const char *str1")
    r_fn = brace_item(r_path.read_text(), "fn opng_strcasecmp(str1:")
    emit(
        "S16", "opng_strcasecmp_valid", ["#include <ctype.h>", "#include <stdint.h>"], [],
        ["int opng_strcasecmp_valid(int8_t left[16], int8_t right[16]);"],
        c_fn + "\n\nint opng_strcasecmp_valid(int8_t left[16], int8_t right[16]) { left[15]=0; right[15]=0; return opng_strcasecmp((char *)left,(char *)right); }",
        "", r_fn,
        "#[no_mangle]\npub fn opng_strcasecmp_valid(left: &mut [i8; 16], right: &mut [i8; 16]) -> i32 { left[15]=0; right[15]=0; opng_strcasecmp(left.as_ptr(),right.as_ptr()) }",
        {"c": str(c_path.relative_to(ROOT)), "rust": str(r_path.relative_to(ROOT))},
        "Force two generated 16-byte strings to be NUL-terminated and compare the scalar return.",
    )


def make_c16() -> None:
    c_path = ROOT / "benchmark/pairs/rq4/optipng_c2saferrust/source/libpng/pngwutil.c"
    r_path = ROOT / "benchmark/pairs/rq4/optipng_c2saferrust/translated/optipng_c2saferrust.rs"
    c_fn = brace_item(c_path.read_text(), "optimize_cmf(png_bytep data")
    r_fn = brace_item(r_path.read_text(), "fn optimize_cmf(data:")
    emit(
        "C16", "optimize_cmf_valid", ["#include <stddef.h>", "#include <stdint.h>"], [],
        ["void optimize_cmf_valid(uint8_t data[2]);"],
        "typedef uint8_t png_byte; typedef png_byte *png_bytep; typedef size_t png_alloc_size_t;\n" + c_fn + "\n\nvoid optimize_cmf_valid(uint8_t data[2]) { optimize_cmf(data, 2); }",
        "", r_fn,
        "#[no_mangle]\npub fn optimize_cmf_valid(data: &mut [u8; 2]) { optimize_cmf(&mut data[..], 2); }",
        {"c": str(c_path.relative_to(ROOT)), "rust": str(r_path.relative_to(ROOT))},
        "Provide the two bytes read by optimize_cmf and fix the valid data_size to two; byte values remain artifact-generated.",
    )


def main() -> None:
    make_c2(); make_c4(); make_s15(); make_s14(); make_c13(); make_s16(); make_c16()


if __name__ == "__main__":
    main()
