#!/usr/bin/env python3
"""Package the exact bzip2 buffer-compression boundary for FLOURINE.

The wrapper supplies fixed backing storage and derives the source length from
an artifact-generated byte.  It does not force the empty-input witness for
S12; zero is one of 32 independently searchable length values.
"""

from __future__ import annotations

import hashlib
import json
import re
from pathlib import Path


ROOT = Path("/home/yunzez/c2rust_testing")
PAIR = ROOT / "benchmark/pairs/rq4/bzip2_c2saferrust"
OUT = ROOT / "results/baseline_artifacts/adapters/flourine/S12"


def sha256(path: Path) -> str:
    return hashlib.sha256(path.read_bytes()).hexdigest()


def without_includes(source: str) -> str:
    return re.sub(r"^\s*#\s*include\s*[<\"][^>\"]+[>\"]\s*$", "", source, flags=re.MULTILINE)


def c_translation_unit() -> str:
    source = PAIR / "source"
    pieces = [
        without_includes((source / name).read_text())
        for name in (
            "bzlib.h",
            "bzlib_private.h",
            "blocksort.c",
            "huffman.c",
            "crctable.c",
            "randtable.c",
            "compress.c",
            "decompress.c",
            "bzlib.c",
        )
    ]
    wrapper = r'''

int bzbuff_compress_packet(int8_t packet[64])
{
    char destination[128];
    unsigned int destination_length = sizeof(destination);
    unsigned int source_length = ((unsigned char)packet[0]) % 32;
    return BZ2_bzBuffToBuffCompress(
        destination,
        &destination_length,
        (char *)&packet[1],
        source_length,
        1,
        0,
        30);
}
'''
    return "\n\n".join(pieces) + wrapper


def rust_dependency_unit() -> str:
    source = (PAIR / "translated/bzip2_c2saferrust.rs").read_text()
    return re.sub(r"(?ms)^#!\[[^\]]*\]\s*", "", source).rstrip() + "\n"


def rust_surface(raw_name: str) -> str:
    return f'''#![feature(core_intrinsics)]
#![feature(extern_types)]
#![feature(linkage)]
#![feature(c_variadic)]
#![feature(register_tool)]
#![register_tool(c2rust)]

include!["/input/{raw_name}"];

#[no_mangle]
pub fn bzbuff_compress_packet(packet: &mut [i8; 64]) -> i32 {{
    let source_length = (packet[0] as u8 % 32) as usize;
    let source = unsafe {{
        std::slice::from_raw_parts(packet.as_ptr().add(1) as *const u8, source_length)
    }};
    let mut destination = vec![0u8; 128];
    BZ2_bzBuffToBuffCompress(&mut destination, source, 1, 0, 30)
}}
'''


def main() -> None:
    input_dir = OUT / "input"
    input_dir.mkdir(parents=True, exist_ok=True)
    json_path = input_dir / "bzbuff_compress_packet.json"
    rust_path = input_dir / "bzbuff_compress_packet.rs"
    raw_path = input_dir / "bzbuff_compress_packet_raw.inc"

    json_path.write_text(
        json.dumps(
            {
                "Includes": [
                    "#include <ctype.h>",
                    "#include <stdint.h>",
                    "#include <stdio.h>",
                    "#include <stdlib.h>",
                    "#include <string.h>",
                ],
                "Defines": [],
                "TypeDefs": [],
                "Globals": [],
                "Structs": [],
                "Function Declarations": [
                    "int bzbuff_compress_packet(int8_t packet[64]);"
                ],
                "Function Implementations": [c_translation_unit()],
                "Enums": [],
            },
            indent=2,
        )
        + "\n"
    )
    raw_path.write_text(rust_dependency_unit())
    rust_path.write_text(rust_surface(raw_path.name))
    metadata = {
        "schema_version": 1,
        "defect": "S12",
        "baseline": "flourine",
        "target": "bzbuff_compress_packet",
        "adapter_kind": "documented_per_function_json_with_bounded_length_wrapper",
        "semantic_rewrite": False,
        "known_witness_encoded": False,
        "sources": {
            "c": "benchmark/pairs/rq4/bzip2_c2saferrust/source/bzip2lib.c",
            "rust": "benchmark/pairs/rq4/bzip2_c2saferrust/translated/bzip2_c2saferrust.rs",
        },
        "wrapper_contract": (
            "Provide 128 bytes of destination storage and up to 31 generated source bytes. "
            "The source length is generated as packet[0] modulo 32; the remaining legal "
            "compression parameters are fixed identically on both sides."
        ),
        "input_sha256": {
            path.name: sha256(path) for path in (json_path, rust_path, raw_path)
        },
    }
    (OUT / "adapter.json").write_text(json.dumps(metadata, indent=2) + "\n")


if __name__ == "__main__":
    main()
