#!/usr/bin/env python3
"""Generate all released-baseline summaries from the canonical result matrix."""

from __future__ import annotations

import json
from collections import Counter
from pathlib import Path


ROOT = Path("/home/yunzez/c2rust_testing")
SOURCE = ROOT / "results/baseline_artifacts/results.json"
OUT = ROOT / "results/baseline_artifacts"
TABLE = ROOT / "c2rust_paper/table/baseline_comparison.tex"
BASELINES = ("rustassure", "flourine", "vert")
DISPLAY = {"rustassure": "RustAssure", "flourine": "FLOURINE", "vert": "VERT"}
OUTCOMES = (
    "detected",
    "missed",
    "unsupported_input",
    "analysis_failure",
    "compile_failure",
    "not_run",
)


def summarize(records: list[dict]) -> dict:
    result = {"schema_version": 1, "source": str(SOURCE.relative_to(ROOT)), "baselines": {}}
    for baseline in BASELINES:
        rows = [row for row in records if row["baseline"] == baseline]
        gates = {
            gate: sorted(row["defect_id"] for row in rows if row["gates"][gate])
            for gate in ("submitted", "accepted", "compiled", "completed", "detected")
        }
        outcomes = {
            outcome: sorted(row["defect_id"] for row in rows if row["outcome"] == outcome)
            for outcome in OUTCOMES
        }
        result["baselines"][baseline] = {
            "denominator": len(rows),
            "gates": gates,
            "gate_counts": {gate: len(ids) for gate, ids in gates.items()},
            "outcomes": outcomes,
            "outcome_counts": {outcome: len(ids) for outcome, ids in outcomes.items()},
            "conditional_detection": {
                "numerator": len(gates["detected"]),
                "denominator": len(gates["completed"]),
            },
        }
    return result


def markdown(summary: dict) -> str:
    lines = [
        "# Released-artifact baseline comparison",
        "",
        "Generated from `results/baseline_artifacts/results.json`; do not edit counts by hand.",
        "",
        "## Funnel",
        "",
        "| Baseline | Submitted | Accepted | Compiled | Completed | Detected | Detected / completed |",
        "|---|---:|---:|---:|---:|---:|---:|",
    ]
    for baseline in BASELINES:
        item = summary["baselines"][baseline]
        count = item["gate_counts"]
        conditional = (
            f"{count['detected']}/{count['completed']}"
            if count["completed"]
            else "--"
        )
        lines.append(
            f"| {DISPLAY[baseline]} | {count['submitted']}/36 | {count['accepted']}/36 | "
            f"{count['compiled']}/36 | {count['completed']}/36 | {count['detected']}/36 | "
            f"{conditional} |"
        )
    lines.extend(
        [
            "",
            "## Final outcomes",
            "",
            "| Baseline | Detected | Missed | Unsupported | Analysis failure | Compile failure | Not run |",
            "|---|---:|---:|---:|---:|---:|---:|",
        ]
    )
    for baseline in BASELINES:
        count = summary["baselines"][baseline]["outcome_counts"]
        lines.append(
            f"| {DISPLAY[baseline]} | {count['detected']} | {count['missed']} | "
            f"{count['unsupported_input']} | {count['analysis_failure']} | "
            f"{count['compile_failure']} | {count['not_run']} |"
        )
    lines.extend(["", "## Defect IDs", ""])
    for baseline in BASELINES:
        lines.append(f"### {DISPLAY[baseline]}")
        lines.append("")
        outcomes = summary["baselines"][baseline]["outcomes"]
        for outcome in OUTCOMES:
            values = ", ".join(outcomes[outcome]) or "none"
            lines.append(f"- `{outcome}`: {values}")
        lines.append("")
    return "\n".join(lines).rstrip() + "\n"


def latex(summary: dict) -> str:
    rows: list[str] = []
    for index, baseline in enumerate(BASELINES):
        item = summary["baselines"][baseline]
        gates = item["gate_counts"]
        outcomes = item["outcome_counts"]
        prefix = "\\rowcolor{gray!4}\n" if index % 2 == 0 else ""
        conditional = (
            f"{gates['detected']}/{gates['completed']}"
            if gates["completed"]
            else "--"
        )
        display = DISPLAY[baseline] + ("$^{\\dagger}$" if baseline == "vert" else "")
        rows.append(
            prefix
            + f"{display} & {gates['submitted']} & {gates['accepted']} & "
            + f"{gates['compiled']} & {gates['completed']} & \\textbf{{{gates['detected']}}} & "
            + f"{conditional} & {outcomes['missed']} & {outcomes['unsupported_input']} & "
            + f"{outcomes['analysis_failure']} & {outcomes['compile_failure']} \\\\"
        )
    return r"""% Generated by scripts/baseline_artifacts/summarize.py.
\begin{center}
\begin{minipage}{\textwidth}
\centering
\captionof{table}{Released-artifact comparison over the 36 confirmed defects.
S/A/C/R/D denotes submitted, accepted, compiled, completed, and detected;
D/R is detection conditional on completed analysis. Unsupported inputs,
analysis failures, compilation failures, and completed misses are separate.}
\label{tab:baseline-comparison}

\scriptsize
\setlength{\tabcolsep}{2.8pt}
\renewcommand{\arraystretch}{1.12}
\begin{tabular}{@{}lrrrrrrrrrr@{}}
\toprule
\rowcolor{gray!12}
\textbf{Baseline} & \textbf{S} & \textbf{A} & \textbf{C} & \textbf{R} &
\textbf{D} & \textbf{D/R} & \textbf{Miss} & \textbf{Unsup.} &
\textbf{A-fail} & \textbf{C-fail} \\
\midrule
""" + "\n".join(rows) + r"""
\bottomrule
\end{tabular}

\vspace{2pt}
\parbox{0.92\textwidth}{\scriptsize All funnel columns use the full
36-defect denominator. $^{\dagger}$VERT has no released external-candidate
interface and is exercised through the fixed adapter described in the text.
A defect is a miss only when the released artifact
completed its analysis without exposing it; unsupported inputs and tool
failures are not counted as semantic misses. A-fail and C-fail denote analysis
and compilation failures.}
\end{minipage}
\end{center}
"""


def main() -> None:
    data = json.loads(SOURCE.read_text())
    records = data["records"]
    assert len(records) == 36 * 3
    assert Counter(row["baseline"] for row in records) == Counter({name: 36 for name in BASELINES})
    summary = summarize(records)
    (OUT / "funnel.json").write_text(json.dumps(summary, indent=2) + "\n")
    (OUT / "SUMMARY.md").write_text(markdown(summary))
    TABLE.write_text(latex(summary))
    print(f"wrote {OUT / 'funnel.json'}, {OUT / 'SUMMARY.md'}, and {TABLE}")


if __name__ == "__main__":
    main()
